### ISSUE TITLE
Error running CanvasAreaGRG tool

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#114]
Error trying to run Canvas Area GRG:

```
Executing: CanvasAreaGRG "7839693.71294265 4085715.31215141 7840856.44136946 4086572.16098378" 100 100 Meters "Feature Set" Lower-Left Alpha-Numeric C:\Users\matt2542\Documents\ArcGIS\Default.gdb\CanvasAreaGRGScript
Start Time: Tue Sep 16 15:21:00 2014
Executing (Canvas Area GRG Script): CanvasAreaGRGScript "7839693.71294265 4085715.31215141 7840856.44136946 4086572.16098378" 100 100 Meters "Feature Set" Alpha-Numeric C:\Users\matt2542\Documents\ArcGIS\Default.gdb\CanvasAreaGRGScript Lower-Left
Start Time: Tue Sep 16 15:21:00 2014
Running script CanvasAreaGRGScript...
Failed script CanvasAreaGRGScript...

Traceback (most recent call last):
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\operational_graphics\toolboxes\Scripts\CanvasAreaGRG.py", line 345, in <module>
    arcpy.ImportToolbox(toolboxPath, "ClearingOperations")
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\__init__.py", line 124, in ImportToolbox
    return import_toolbox(input_file, module_name)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\toolbox_code.py", line 434, in import_toolbox
    toolbox = gp.createObject("Toolbox", tbxfile)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\geoprocessing\_base.py", line 379, in createObject
    self._gp.CreateObject(*gp_fixargs(args, True)))
IOError: The toolbox file C:\Users\matt2542\Documents\toolboxes\ClearingOperations.tbx was not found.

Failed to execute (Canvas Area GRG Script).
Failed at Tue Sep 16 15:21:01 2014 (Elapsed Time: 0.91 seconds)
Failed to execute (CanvasAreaGRG).
Failed at Tue Sep 16 15:21:01 2014 (Elapsed Time: 1.12 seconds)
```

The lines it is referencing are:

```
toolboxPath = os.path.dirname(os.path.dirname(arcpy.env.workspace)) + "\\toolboxes\ClearingOperations.tbx"
arcpy.ImportToolbox(toolboxPath, "ClearingOperations")
```

the ```toolboxPath``` variable is pointing to a path that doesn't exist.

**Comment by mfunk** [comment]
@jscott11 do you have any thoughts on this one? It's been awhile and somehow with your work on the tools I think you might have either come across this already or fixed it already.

**Comment by mfunk** [comment]
I've been working on this tool and I'm unable to reproduce the same error. Have run the tool in ArcMap, ArcGIS Pro, and non-mapping (automated tests). Closing.
