### ISSUE TITLE
Point Target GRG Error

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#186]
@jscott11 I was testing these tools, and received the following error message after I followed these steps:
1. Opened the Point Target GRG Tool (just downloaded as of afternoon of 13 JAN) in ArcGIS Pro (1.0.0, Build 1797)
2. Set the following parameters:
![image](https://cloud.githubusercontent.com/assets/5016557/5731096/ac31c754-9b34-11e4-9627-b71a53b01105.png)
3. Clicked Run
4. Received the following error message:
```Start Time: Tue Jan 13 14:56:35 2015
Executing (Point Target GRG Script): PointTargetGRGScript "Red Green Map Notes\Red Green - Point Notes" 5 7 100 100 Meters "Feature Set" Alpha-Numeric C:\Users\joe7503\Documents\ArcGIS\Projects\ClearingOperations\ClearingOperations.gdb\PointTargetGRGScript Lower-Left
Start Time: Tue Jan 13 14:56:35 2015
Running script PointTargetGRGScript...
Creating Fishnet Grid
Failed script PointTargetGRGScript...
Traceback (most recent call last):
  File "C:\Users\joe7503\Documents\GitHub\solutions-geoprocessing-toolbox\operational_graphics\toolboxes\Scripts\PointTargetGRG.py", line 425, in <module>
    arcpy.CreateFishnet_ClearingOperations(tempOutput, originCoordinate, yAxisCoordinate, 0, 0, str(numberCellsHo), str(numberCellsVert), oppCornerCoordinate, "NO_LABELS", fullExtent, "POLYGON")
AttributeError: 'module' object has no attribute 'CreateFishnet_ClearingOperations'
Failed to execute (Point Target GRG Script).
Failed at Tue Jan 13 14:56:36 2015 (Elapsed Time: 0.35 seconds)
Failed to execute (PointTargetGRG).
Failed at Tue Jan 13 14:56:36 2015 (Elapsed Time: 0.57 seconds)```

Also, I ran it with the ```Grid Size``` option, using the below parameters:
![image](https://cloud.githubusercontent.com/assets/5016557/5731148/2a9e9dec-9b35-11e4-85b3-3d884827c9ab.png)

... and received this error:
```Start Time: Tue Jan 13 15:01:30 2015
Executing (Point Target GRG Script): PointTargetGRGScript "Red Green Map Notes\Red Green - Point Notes" 5 7 0 0 Meters "Red Green Map Notes\Red Green - Polygon Notes" Alpha-Numeric C:\Users\joe7503\Documents\ArcGIS\Projects\ClearingOperations\ClearingOperations.gdb\PointTargetGRGScript Lower-Left
Start Time: Tue Jan 13 15:01:31 2015
Running script PointTargetGRGScript...
Creating Fishnet Grid
Failed script PointTargetGRGScript...
Traceback (most recent call last):
  File "C:\Users\joe7503\Documents\GitHub\solutions-geoprocessing-toolbox\operational_graphics\toolboxes\Scripts\PointTargetGRG.py", line 425, in <module>
    arcpy.CreateFishnet_ClearingOperations(tempOutput, originCoordinate, yAxisCoordinate, 0, 0, str(numberCellsHo), str(numberCellsVert), oppCornerCoordinate, "NO_LABELS", fullExtent, "POLYGON")
AttributeError: 'module' object has no attribute 'CreateFishnet_ClearingOperations'
Failed to execute (Point Target GRG Script).
Failed at Tue Jan 13 15:01:32 2015 (Elapsed Time: 1.32 seconds)
Failed to execute (PointTargetGRG).
Failed at Tue Jan 13 15:01:32 2015 (Elapsed Time: 1.58 seconds)```

Thanks!

**Comment by joebayles** [comment]
@jscott11 I ran it again and didn't get quite as far...
```Start Time: Tue Jan 13 16:21:59 2015
Executing (Point Target GRG Script): PointTargetGRGScript "Red Green Map Notes\Red Green - Point Notes" 5 7 0 0 Meters "Red Green Map Notes\Red Green - Polygon Notes" Alpha-Numeric C:\Users\joe7503\Documents\ArcGIS\Projects\ClearingOperations\ClearingOperations.gdb\PointTargetGRGScript Lower-Left
Start Time: Tue Jan 13 16:22:00 2015
Running script PointTargetGRGScript...
Failed script PointTargetGRGScript...
Traceback (most recent call last):
  File "C:\Users\joe7503\Documents\GitHub\solutions-geoprocessing-toolbox\operational_graphics\toolboxes\Scripts\PointTargetGRG.py", line 423, in <module>
    arcpy.ImportToolbox(toolboxPath, "ClearingOperations")
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\__init__.py", line 124, in ImportToolbox
    return import_toolbox(input_file, module_name)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\toolbox_code.py", line 443, in import_toolbox
    toolbox = gp.createObject("Toolbox", tbxfile)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 371, in createObject
    self._gp.CreateObject(*gp_fixargs(args, True)))
OSError: The toolbox file C:\Users\joe7503\Documents\ArcGIS\Projects\ClearingOperations\ClearingOperations.tbx was not found.
Failed to execute (Point Target GRG Script).
Failed at Tue Jan 13 16:22:01 2015 (Elapsed Time: 1.30 seconds)
Failed to execute (PointTargetGRG).
Failed at Tue Jan 13 16:22:01 2015 (Elapsed Time: 1.56 seconds)```

**Comment by jscott11** [comment]
@joebayles Can you send me, or point me to where the Pro Clearing Operations template you are using is? I'm not able to replicate this, and I think it's a folder structure issue that I'll need to fix in the script. I need to see how it's setup though, if possible.

**Comment by joebayles** [comment]
Janette, I had to remove the toolbox I was using because I couldn't package with it in there, but if you open up the ClearingOperations.ppkx [here](https://esri.box.com/s/1g63k7ht4d8frpkxd8ymr9i5u2w1dyz2) and then add the toolbox you're using (I added it straight from my GitHub folder like this:
![image](https://cloud.githubusercontent.com/assets/5016557/5862807/95e77736-a229-11e4-8112-db6e960b4aeb.png)
... it should perform just like I said above.

Thanks!

**Comment by jscott11** [comment]
@joebayles Thanks! I'm seeing the error now! Hopefully I should have it fixed shortly.

**Comment by joebayles** [comment]
Awesome! :thumbsup:

**Comment by jscott11** [comment]
@joebayles When you have a chance, can you retest this and #185 with the latest? 
(crossing my fingers!)

**Comment by joebayles** [comment]
I'll do it today... thanks @jscott11! I'm sure it'll work great!

**Comment by joebayles** [comment]
Verified... works great!

Aside, I found a few mis-spellings in the tool, i.e.
![image](https://cloud.githubusercontent.com/assets/5016557/5927976/c70f4ef0-a62b-11e4-96e3-b09536e6f3fc.png)

I'll fix them and send the pull request.
