### ISSUE TITLE
Some issues with Incident Hot Spots

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#267]
Some issues with **Incident Hot Spots** in Incident Analysis Tools.
* Needs updates to parameter names:
     * [X] First parameter is *Input Features*. We could probably make this a little more clear and specific to this tool. Something like *Input Incident Point Features* might be better.
     * [X] *Bounding Polygons Defining Where Incidents Are Possible* is more of a description than a name. *Input Incident Boundary Features* might work better.

* [x] Unable to have tool run in ArcGIS Pro 1.1 Build 3100. But this does NOT happen with ArcMap 10.3. With the following parameters:
     * Input Incident Point Features: *All Incidents*
     * Bounding Polygons...: *District Outline*
     * Output Features: *C:\Workspace\Test\TestIncidentAnalysis\Test_IA\Test_IA.gdb\ihsPRO001*
     * When run:

```
Start Time: Mon May 04 14:04:35 2015
Executing (Optimized Hot Spot Analysis): OptimizedHotSpotAnalysis "Incidents\All Incidents" C:\Workspace\Test\TestIncidentAnalysis\Test_IA\Test_IA.gdb\ihsPRO001 # COUNT_INCIDENTS_WITHIN_FISHNET_POLYGONS "District Outline" # #
Start Time: Mon May 04 14:04:50 2015
Running script OptimizedHotSpotAnalysis...
Failed script OptimizedHotSpotAnalysis...
Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\Scripts\OptimizedHotSpotAnalysis.py", line 991, in <module>
    setupOptHotSpot()
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\Scripts\OptimizedHotSpotAnalysis.py", line 222, in setupOptHotSpot
    selectionType = UTILS.getSelectionType(featureLayerInit)
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\Scripts\SSUtilities.py", line 155, in getSelectionType
    fidSet = info.FIDSet
AttributeError: DescribeData: Method FIDSet does not exist
Failed to execute (Optimized Hot Spot Analysis).
Failed at Mon May 04 14:05:05 2015 (Elapsed Time: 14.07 seconds)
Failed to execute (IncidentHotSpots).
Failed at Mon May 04 14:05:05 2015 (Elapsed Time: 29.85 seconds)
```

**Comment by mfunk** [comment]
I updated to ArcGIS Pro 1.1 Build 3112 and the tool is running as expected now:

```
 
Parameters
Input Incident Point Features	Incidents\All Incidents
Input Incident Boundary Features	District Outline
Output Features	C:\Workspace\Test\TestIncidentAnalysis\Test_IA\Test_IA.gdb\ihs_of_001
 
Messages
Start Time: Tue May 05 09:41:25 2015
Executing (Optimized Hot Spot Analysis): OptimizedHotSpotAnalysis "Incidents\All Incidents" C:\Workspace\Test\TestIncidentAnalysis\Test_IA\Test_IA.gdb\ihs_of_001 # COUNT_INCIDENTS_WITHIN_FISHNET_POLYGONS "District Outline" # #
Start Time: Tue May 05 09:41:31 2015
Running script OptimizedHotSpotAnalysis...
************************** Initial Data Assessment ***************************
Making sure there are enough incidents for analysis....
- There are 4598 valid input features.
Evaluating the bounding polygon feature class....
- The total study area is 59289084.5583 Meters.
Looking for locational outliers....
- There were 28 outlier locations; these will not be used to compute the polygon cell size.
**************************** Incident Aggregation ****************************
Creating fishnet polygon mesh to use for aggregating incidents....
- Using a polygon cell size of 133.0000 Meters
Counting the number of incidents in each polygon cell....
- Analysis is performed on all polygon cells within the bounding polygon feature class.
Evaluating incident counts and number of polygons....
- The aggregation process resulted in 3554 weighted polygons.
- Incident Count Properties:
Min:        0.0000
        Max:       50.0000
        Mean:       1.2938
        Std. Dev.:  2.9694
***************************** Scale of Analysis ******************************
Looking for an optimal scale of analysis by assessing the intensity of clustering at increasing distances....
- The optimal fixed distance band is based on peak clustering found at 799.0000 Meters
***************************** Hot Spot Analysis ******************************
Finding statistically significant clusters of high and low incident counts....
- There are 1239 output features statistically significant based on an FDR correction for multiple testing and spatial dependence.
*********************************** Output ***********************************
Creating output feature class: C:\Workspace\Test\TestIncidentAnalysis\Test_IA\Test_IA.gdb\ihs_of_001
- Red output features represent hot spots where high incident counts cluster.
- Blue output features represent cold spots where low incident counts cluster.
Completed script OptimizedHotSpotAnalysis...
Succeeded at Tue May 05 09:42:22 2015 (Elapsed Time: 50.09 seconds)
Succeeded at Tue May 05 09:42:22 2015 (Elapsed Time: 56.46 seconds)
```
