### ISSUE TITLE
Error importing the Visibility and Range toolbox

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#335]
When you try to import the **Visibility and Range Tools_10.3.tbx** you get a syntax error from some internal script.

1) Open Python prompt in ArcCatalog/ArcMap/etc.
2) *arcpy.ImportToolbox(<path to >\"Visibility and Range Tools_10.3.tbx',"VandR")*

'''
>>> arcpy.ImportToolbox(r'C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\toolboxes\Visibility and Range Tools_10.3.tbx',"VandR")
Runtime error 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\__init__.py", line 124, in ImportToolbox
    return import_toolbox(input_file, module_name)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\toolbox_code.py", line 440, in import_toolbox
    mymodule = generate_toolbox_module(toolbox, None, False, False, False, module_name, use_alt_alias)
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\toolbox_code.py", line 414, in generate_toolbox_module
    'exec')
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\toolboxes\Visibility and Range Tools_10.3.tbx", line 561
    def RadialLineofSight-MultipleTowers(Input_Surface=None, Force_visibility_to_infinity=None, Defensive_Position_Feature_Class=None, Defensive_Position_Description_Field=None, Defensive_Position_Height_Field=None, Output_Workspace=None, Output_Prefix=None):
                         ^
SyntaxError: invalid syntax
>>> 
'''

**Comment by mfunk** [comment]
Fixed this one in building *HLZTouchdownPointsTestCase.py*. The toolbox was corrupted and the paths to the script tools were broken. Had to manually rebuild the TBX and copy the doc/properties over.
