### ISSUE TITLE
test_Choose_Field_Value_Script_Tool_Pro fails with "Tool or environment not found"

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#342]
Running the new unittest for **ChooseFieldValueScriptTool** in Python 3.4 is failing because tool cannot be found:

```
test_Choose_Field_Value_Script_Tool_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 141, in test_Choose_Field_Value_Script_Tool_Pro
    self.Choose_Field_Value_Script_Tool(self.tbxProFolderPath)
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 158, in Choose_Field_Value_Script_Tool
    result = arcpy.ChooseFieldValueScriptTool_tdpoints(self.inputAirframeTable, inputField, inputChoice)
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\capability\toolboxes\Helicopter Landing Zone Tools.tbx", line 68, in ChooseFieldValueScriptTool
    JLVm9rq1M9XzgUdq+CfGnxE8R/EDVYr/AFjUZBJA6SW1tYvJBbWsiZ2SRJvJWQEsRISXBYgMFAUd
AttributeError: Object: Tool or environment <ChooseFieldValueScriptTool_tdpoints> not found
```

The tool script works in ArcGIS for Desktop (test_Choose_Field_Value_Script_Tool_Desktop) works just fine. Tool can be run in ArcGIS Pro, but not in Python 3.4

**Comment by mfunk** [comment]
This was related to a bad **Helicopter Landing Zone Tools.tbx** that got corrupted somehow and had a bad path to the tool. was fixed now and test are running fine.
