### ISSUE TITLE
Error testing LookUpERG in ERG.py

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#343]
@dmMartin (just an FYI ...)
This is an issue with unittesting only, and the tool itself seems to be working with the same inputs.
In building a unittest framework we are trying to independently test components of the **ERG Tools.pyt**, including the source script ERG.py. In three of the cases we are testing the table lookup in the *LookUpERG* module, by passing it values and checking the results against the the ERG Table 1 values.
Three test cases are used in the unittest, two produce correct results. The third is failing with different errors in Python 2.7 and Python 3.4.

The test code that is being used is as follows:
```
    def test_LookUpERG003(self):
        '''
        test case three
        ERG Table 1, p316: ID No. 2810 Sarin
        '''
        if TestUtilities.DEBUG == True: print("         ERGScript.test_LookUpERG003")
        inChemical = 'Sarin (when used as a weapon)'
        inPlacardID = '2810'
        inSpillSize = 'Large' #'Large' or 'Small'
        inTimeOfDay = 'Night' #'Day' or 'Night'
        outResult = self.LookUpERG(inChemical, inPlacardID, inSpillSize, inTimeOfDay, self.dbfFolderPath)
        if TestUtilities.DEBUG == True: print("outResult: " + str(outResult))
        self.assertEqual(outResult[0], 400.0) # Initial Isolation Distance
        self.assertEqual(outResult[1], 4900.0) # Protective Action Distance
        self.assertEqual(outResult[2], 'Sarin (when used as a weapon)') # Materials
        self.assertEqual(outResult[3], 153) # GuideNum
        return

    def LookUpERG(self, pChemical, pPlacardID, pSpillSize, pTimeOfDay, pERGdbf):
        ''' test ERG.py's LookUpERG submodule '''
        if TestUtilities.DEBUG == True: print("         ERGScript.LookUpERG: " + str(pChemical))
        outLookUpERGTuple = ERG.LookUpERG(pChemical, pPlacardID, pSpillSize, pTimeOfDay, pERGdbf)
        return outLookUpERGTuple
```
For Python 3.4 the unittest shows this as the error message (edited for length):

```
Test success: False
RESULTS =================================================

Number of tests run: 11
Number of errors: 1
Number of failures: 0

ERRORS =================================================

test_ERGByChemical_003 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 113, in test_ERGByChemical_003
    inputDayOrNight, inputLargeOrSmall)
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 133, in ERGByChemical
    outputERGLines)
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\capability\toolboxes\ERG Tools.pyt", line 62, in ERGByChemical
    datatype="GPLong",
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\capability\toolboxes\ERG Tools.pyt", line 59, in ERGByChemical
    param2 = arcpy.Parameter(
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000800: The value is not a member of 1,1-Dimethylhydrazine | 1,2-Dimethylhydrazine | 2-Chloroethanal | 2-Methyl-2-heptanethiol | 3,5-Dichloro-2,4,6-trifluoropyridine | AC (when used as a weapon) | 

[text removed here]

Vinyltrichlorosilane (when spilled in water) | Vinyltrichlorosilane, stabilized (when spilled in water) | Zinc dithionite (when spilled in water) | Zinc hydrosulfite (when spilled in water) | Zinc hydrosulphite (
when spilled in water) | n-Butyl chloroformate | n-Butyl isocyanate | n-Propyl chloroformate | n-Propyl isocyanate | sec-Butyl chloroformate | tert-Butyl isocyanate | tert-Octyl mercaptan.
Failed to execute (ERGByChemical).



END OF TEST =========================================
```

In Python 2.7 the same test errors, but with a different message:

```
Test success: False
RESULTS =================================================

Number of tests run: 11
Number of errors: 1
Number of failures: 0

ERRORS =================================================

test_ERGByChemical_003 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 113, in test_ERGByChemical_003
    inputDayOrNight, inputLargeOrSmall)
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 133, in ERGByChemical
    outputERGLines)
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\capability\toolboxes\ERG Tools.pyt", line 62, in ERGByChemical
    datatype="GPLong",
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000800: The value is not a member of 1,1-Dimethylhydrazine | 1,2-Dimethylhydrazine | 2-Chloroethanal | 2-Methyl-2-heptanethiol | 3,5-Dichloro-2,4,6-trifluoropyridine | AC (when used as a weapon) | Acetone cyanohydr
in, stabilized (when spilled in water) | Acetyl bromide (when spilled in water) | Acetyl chloride (when spilled in water) | Acetyl iodide (when spilled in water) | Acrolein, stabilized | Adamsite (when used as a weapon)

[text removed here]

 Vinyltrichlorosilane (when spilled in water) | Vinyltrichlorosilane, stabilized (when spilled in water) | Zinc dithionite (when spilled in water) | Zinc hydrosulfite (when spilled in water) | Zinc hydrosulphite (
when spilled in water) | n-Butyl chloroformate | n-Butyl isocyanate | n-Propyl chloroformate | n-Propyl isocyanate | sec-Butyl chloroformate | tert-Butyl isocyanate | tert-Octyl mercaptan.
Failed to execute (ERGByChemical).
```

You should be able to see the tests as the are being written in my *unittest* branch of the repo. This is being tested in **ERGScriptTestCase.py**.

Steps:
1) Get the repo download from the *unittest* branch of the *mfunk* fork of this repo
2) Open a command prompt
3) cd .\utils\test
4) comment out the line: *testSuite.addTests(HelicopterLandingZoneToolsTestSuite.getHLZTestSuite...*
4) run TestKickStart.bat

**Comment by mfunk** [comment]
EBCAK on this one. Can't read my own errors. Closing...
