### ISSUE TITLE
Errors for all tests from UnitTestUtilities.py ("Bad Path")

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#372]
@JudTown17  It seems that we are hitting an error on every test in the unittest famework, for Python 2.7 and Python 3.4 when we get to **checkFilePaths** in *UnitTestUtilities.py*.

I'm getting this with ArcGIS 10.4 by:
1) open shell from GitHub for Windows
2) cd utils\test
3) TestKickStart.bat

The repeated error is basically:

```
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data
```

Basically it seems that the "data" folder doesn't exist, so the DataDownload part isn't being reached.

The full error output is as follows:

```
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox [unittest]> cd utils\test
C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test [unittest]> .\TestKickStart.bat
Python 3.4 Tests ===============================
Debug messaging is OFF
Logging results to: SGT_2015-December-21_11-58-19_seq0.log
adding test: test_sun_position_analysis_pro
adding test: test_Choose_Field_Value_Script_Tool_Pro
adding test: test_MinimumBoundingFishnet_Pro
adding test: test_HLZ_Touchdown_Points_001_Pro
adding test: test_ERGByChemical_001
adding test: test_ERGByChemical_002
adding test: test_ERGByChemical_003
adding test: test_ERGByPlacard_001
adding test: test_ERGByPlacard_002
adding test: test_LookUpERG001
adding test: test_LookUpERG002
adding test: test_LookUpERG003
adding test: test_GetProjectedPoint001
adding test: test_GetProjectedPoint002
adding test: test_GetProjectedPoint003
adding test: test_GetProjectedPoint004
running 16 tests...
ArcPy works
Zip Name: test_sun_position.gdb.zip
Extracting zip...
Deleting zip...
Downloaded test_sun_position.gdb to C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\visibility_tests\data
Testing Sun Position Analysis (Pro).
Importing toolbox...
Setting up inputs...
Set date...
Set UTCAfg...
Set output hillshade...
Running tool (Sun Position and Hillshade)
PYTHON ERRORS:
Traceback info:
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\visibility_tests\SunPositionAndHillshadeTestCase.py", line 108, in test_sun_position_analysis
    self.assertEqual(rasMaximum, float(0))

Error Info:
-2.0 != 0.0

ArcPy ERRORS:
Start Time: Mon Dec 21 11:59:03 2015
Number of unique values = 51
Succeeded at Mon Dec 21 11:59:03 2015 (Elapsed Time: 0.03 seconds)

ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
Test success: False
RESULTS =================================================

Number of tests run: 16
Number of errors: 15
Number of failures: 0

ERRORS =================================================

test_Choose_Field_Value_Script_Tool_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 70, in setUp
    self.tbxDesktopFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_MinimumBoundingFishnet_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 70, in setUp
    self.tbxDesktopFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_HLZ_Touchdown_Points_001_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 70, in setUp
    self.tbxDesktopFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByChemical_001 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 59, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByChemical_002 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 59, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByChemical_003 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 59, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByPlacard_001 (capability_tests.ERGByPlacardTestCase.ERGByPlacard)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByPlacardTestCase.py", line 58, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByPlacard_002 (capability_tests.ERGByPlacardTestCase.ERGByPlacard)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByPlacardTestCase.py", line 58, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_LookUpERG001 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_LookUpERG002 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_LookUpERG003 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint001 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint002 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint003 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint004 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data


END OF TEST =========================================

Python 2.7 Tests ===============================
Debug messaging is OFF
Logging results to: SGT_2015-December-21_11-59-48_seq0.log
adding test: test_sun_position_analysis_desktop
adding test: test_Choose_Field_Value_Script_Tool_Desktop
adding test: test_MinimumBoundingFishnet_Desktop
adding test: test_HLZ_Touchdown_Points_001_Desktop
adding test: test_ERGByChemical_001
adding test: test_ERGByChemical_002
adding test: test_ERGByChemical_003
adding test: test_ERGByPlacard_001
adding test: test_ERGByPlacard_002
adding test: test_LookUpERG001
adding test: test_LookUpERG002
adding test: test_LookUpERG003
adding test: test_GetProjectedPoint001
adding test: test_GetProjectedPoint002
adding test: test_GetProjectedPoint003
adding test: test_GetProjectedPoint004
running 16 tests...
ArcPy works
Scratch already exists
Testing Sun Position Analysis (Desktop).
Importing toolbox...
Setting up inputs...
Set date...
Set UTCAfg...
Set output hillshade...
Running tool (Sun Position and Hillshade)
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
ArcPy works
Test success: False
RESULTS =================================================

Number of tests run: 16
Number of errors: 15
Number of failures: 0

ERRORS =================================================

test_Choose_Field_Value_Script_Tool_Desktop (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 70, in setUp
    self.tbxDesktopFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_MinimumBoundingFishnet_Desktop (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 70, in setUp
    self.tbxDesktopFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_HLZ_Touchdown_Points_001_Desktop (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 70, in setUp
    self.tbxDesktopFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByChemical_001 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 59, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByChemical_002 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 59, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByChemical_003 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 59, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByPlacard_001 (capability_tests.ERGByPlacardTestCase.ERGByPlacard)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByPlacardTestCase.py", line 58, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_ERGByPlacard_002 (capability_tests.ERGByPlacardTestCase.ERGByPlacard)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByPlacardTestCase.py", line 58, in setUp
    self.tbxFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_LookUpERG001 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_LookUpERG002 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_LookUpERG003 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint001 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint002 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint003 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data

test_GetProjectedPoint004 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 71, in setUp
    self.testDataFolderPath])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 168, in checkFilePaths
    raise Exception('Bad Path: ' + str(path2check))
Exception: Bad Path: C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data


END OF TEST =========================================

Press any key to continue . . .

```

**Comment by mfunk** [comment]
Verified.
