### ISSUE TITLE
HLZ Touchdown point test errors in Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#387]
Running the unittests I came across the following errors in the HLZ Touchdown point tests:

```
RESULTS =================================================

Number of tests run: 23
Number of errors: 11
Number of failures: 0

ERRORS =================================================

test_Choose_Field_Value_Script_Tool_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 94, in setUp
    self.inputSlope])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 175, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1230, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb" does not exist

test_MinimumBoundingFishnet_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 94, in setUp
    self.inputSlope])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 175, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1230, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb" does not exist

test_HLZ_Touchdown_Points_001_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 94, in setUp
    self.inputSlope])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 175, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1230, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb" does not exist
```

All of the tools point to a file geodatabase that the tools can't find: *.\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb*.

Repro the problem by running the tests: **.\solutions-geprocessing-toolbox\utils\tests\TestKickStart.bat**

**Comment by mfunk** [comment]
The problem here is that the data for the HLZ template was never downloaded, and therefore the geodatabase didn't exist. Added the relevant info for the test to the test case header and tested it, but hitting a new error with **DataDownload.py**

@JudTown17

**Comment by mfunk** [comment]
This guy is still failing with the same error:

```
test_Choose_Field_Value_Script_Tool_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 104, in setUp
    self.inputSlope])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 175, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1230, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb" does not exist

test_MinimumBoundingFishnet_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 104, in setUp
    self.inputSlope])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 175, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1230, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb" does not exist

test_HLZ_Touchdown_Points_001_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 104, in setUp
    self.inputSlope])
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\UnitTestUtilities.py", line 175, in checkGeoObjects
    desc = arcpy.Describe(object2Check)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1230, in Describe
    return gp.describe(value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 368, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
OSError: "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\data\test_hlz_tools.gdb" does not exist
```
