### ISSUE TITLE
ERG errors in PRO unittest

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#389]
In testing for #385 the following errors for the **ERG Tools*** came up:

```
test_ERGByChemical_002 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 69, in setUp
    self.inputPoint = ERGTestUtils.getInputPointFC()
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 41, in getInputPointFC
    fc = getInputPointFCFromXY(77.0, 38.9)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_ERGByChemical_003 (capability_tests.ERGByChemicalTestCase.ERGByChemical)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByChemicalTestCase.py", line 69, in setUp
    self.inputPoint = ERGTestUtils.getInputPointFC()
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 41, in getInputPointFC
    fc = getInputPointFCFromXY(77.0, 38.9)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_ERGByPlacard_001 (capability_tests.ERGByPlacardTestCase.ERGByPlacard)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByPlacardTestCase.py", line 68, in setUp
    self.inputPoint = ERGTestUtils.getInputPointFC()
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 41, in getInputPointFC
    fc = getInputPointFCFromXY(77.0, 38.9)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_ERGByPlacard_002 (capability_tests.ERGByPlacardTestCase.ERGByPlacard)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGByPlacardTestCase.py", line 68, in setUp
    self.inputPoint = ERGTestUtils.getInputPointFC()
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 41, in getInputPointFC
    fc = getInputPointFCFromXY(77.0, 38.9)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_GetProjectedPoint001 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 155, in test_GetProjectedPoint001
    inputPoint = ERGTestUtils.getInputPointFC()
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 41, in getInputPointFC
    fc = getInputPointFCFromXY(77.0, 38.9)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_GetProjectedPoint002 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 165, in test_GetProjectedPoint002
    inputPoint = ERGTestUtils.getInputPointFCFromXY(-121.844234,36.586438)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_GetProjectedPoint003 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 175, in test_GetProjectedPoint003
    inputPoint = ERGTestUtils.getInputPointFCFromXY(-68.609535, 46.178194)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).


test_GetProjectedPoint004 (capability_tests.ERGScriptTestCase.ERGTest)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGScriptTestCase.py", line 185, in test_GetProjectedPoint004
    inputPoint = ERGTestUtils.getInputPointFCFromXY(-98.233824, 26.654716)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\ERGTestUtils.py", line 53, in getInputPointFCFromXY
    sr)[0]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1361, in CreateFeatureclass
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 1358, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(*gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spat
ial_grid_3), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 500, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).
```

All of these seem to point to the same problem:

```
arcgisscripting.ExecuteError: ERROR 000258: Output in_memory\tempfc already exists
Failed to execute (CreateFeatureclass).
```

**Comment by mfunk** [comment]
Tests are working as expected.
