### ISSUE TITLE
Python 2/3 errors in DataDownload.py

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#435]
Running the tests I'm getting double errors...

```
test_Choose_Field_Value_Script_Tool_Pro (capability_tests.HLZTouchdownPointsTestCase.HLZTouchdownPoints)Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\DataDownload.py", line 58, in saveOnlineDataAsZip
    (zipFile, headers) = urllib.urlretrieve(url, zipName)
AttributeError: 'module' object has no attribute 'urlretrieve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\capability_tests\HLZTouchdownPointsTestCase.py", line 86, in setUp
    self.dataDownloadURL)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\DataDownload.py", line 85, in runDataDownload
    zipFile = saveOnlineDataAsZip(url, zipName)
  File "C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\DataDownload.py", line 63, in saveOnlineDataAsZip
    (zipFile, headers) = urllib.request.urlretrieve(url, zipName)
  File "C:\Python34\lib\urllib\request.py", line 186, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

The first error is relating to the following code (lines 52 - 64) in **DataDownload.py**:

```
def saveOnlineDataAsZip(url, zipName):
    ''' Save the zip file from the specified url to the current directory, passing in '''
    ''' the name to use for the saved zip file '''
    try:
        # Python 2
        import urllib  
        (zipFile, headers) = urllib.urlretrieve(url, zipName)
        return zipFile
    except:
        # Python 3
        import urllib.request
        (zipFile, headers) = urllib.request.urlretrieve(url, zipName)
        return zipFile
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043794931)

**Comment by mfunk** [comment]
Not seeing this problem anymore.
