### ISSUE TITLE
Error after running ClusterAnalysisTestCase.test_cluster_analysis_pro

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#457]
Getting an error in the test for Cluster Analysis on Pro that is crashing the whole test framework. At the very end the error message is pointing to...

```
SyntaxError: invalid or missing encoding declaration for 'D:\\GitHub\\solutions-geoprocessing-toolbox\\patterns\\toolboxes\\Incident Analysis Tools.tbx'
```

Seems like the pro toolbox *Incident Analysis Tools.tbx* is being converted in Python somehow.

Full error is below:

```
.....ClusterAnalysisTestCase.test_cluster_analysis_pro
Running tool (Cluster Analysis)
.....ClusterAnalysisTestCase.tearDown
UnitTestUtilities - deleteScratch
Deleted scratch
Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\tokenize.py", line 392, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TestRunner.py", line 183, in <module>
    main()
  File "TestRunner.py", line 71, in main
    result = runTestSuite()
  File "TestRunner.py", line 143, in runTestSuite
    testSuite.run(result)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\case.py", line 628, in __call__
    return self.run(*args, **kwds)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\case.py", line 588, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\case.py", line 518, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\result.py", line 17, in inner
    return method(self, *args, **kw)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\result.py", line 114, in addError
    self.errors.append((test, self._exc_info_to_string(err, test)))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\unittest\result.py", line 184, in _exc_info_to_string
    msgLines = traceback.format_exception(exctype, value, tb)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\traceback.py", line 153, in _format_exception_iter
    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\traceback.py", line 18, in _format_list_iter
    for filename, lineno, name, line in extracted_list:
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\traceback.py", line 65, in _extract_tb_or_stack_iter
    line = linecache.getline(filename, lineno, f.f_globals)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\linecache.py", line 42, in getlines
    return updatecache(filename, module_globals)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\linecache.py", line 130, in updatecache
    with tokenize.open(fullname) as fp:
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\tokenize.py", line 456, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\tokenize.py", line 433, in detect_encoding
    encoding = find_cookie(first)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\tokenize.py", line 397, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'D:\\GitHub\\solutions-geoprocessing-toolbox\\patterns\\toolboxes\\Incident Analysis Tools.tbx'
'One or more tests failed'
```

**Comment by mfunk** [comment]
With some more direct error handling added I get slightly different message:

```
.....ClusterAnalysisTestCase.test_cluster_analysis_pro
Running tool (Cluster Analysis)
.....ClusterAnalysisTestCase.tearDown
UnitTestUtilities - deleteScratch
Deleted scratch
UnitTestUtilities - handleGeneralError
PYTHON ERRORS:
Traceback info:
  File "TestRunner.py", line 157, in runTestSuite
    testSuite.run(result)

Error Info:
invalid or missing encoding declaration for 'D:\\GitHub\\solutions-geoprocessing-toolbox\\patterns\\toolboxes\\Incident Analysis Tools.tbx'

ArcPy ERRORS:
Start Time: Thursday, September 15, 2016 6:13:26 PM
Succeeded at Thursday, September 15, 2016 6:13:26 PM (Elapsed Time: 0.04 seconds)

UnitTestUtilities - handleGeneralError
PYTHON ERRORS:
Traceback info:
  File "TestRunner.py", line 101, in resultsHeader
    msg += "Number of tests run: " + str(result.testsRun) + "\n"

Error Info:
'NoneType' object has no attribute 'testsRun'

ArcPy ERRORS:
Start Time: Thursday, September 15, 2016 6:13:26 PM
Succeeded at Thursday, September 15, 2016 6:13:26 PM (Elapsed Time: 0.04 seconds)

None
UnitTestUtilities - handleGeneralError
PYTHON ERRORS:
Traceback info:
  File "TestRunner.py", line 84, in logTestResults
    if len(result.errors) > 0:

Error Info:
'NoneType' object has no attribute 'errors'

ArcPy ERRORS:
Start Time: Thursday, September 15, 2016 6:13:26 PM
Succeeded at Thursday, September 15, 2016 6:13:26 PM (Elapsed Time: 0.04 seconds)
```

**Comment by mfunk** [comment]
After talking with one of the guys on the GP team it seems that this is a problem with *linecache.py* trying to read through an error traceback to open up the Pro TBX, which won't happen as it's a binary file. This is a problem in Python, not this script. The workaround is to wrap the test with a try/except and use **self.fail()** in the *unittest* library to circumvent the traceback/linecache problem.
