### ISSUE TITLE
Feature count error in test_incident_hot_spots_desktop (and Pro)

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#476]
Automated tests for ArcGIS 10.5 (ArcMap) throwing an error for Hot Spots in Incident Analysis.

## Expected Behavior
Should not error. Something in 10.5 that is changing how the features are being analyzed?

## Current Behavior
Error from the automated tests in Desktop:

```
test_incident_hot_spots_desktop (patterns_tests.IncidentHotSpotsTestCase.IncidentHotSpotsTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentHotSpotsTestCase.py", line 92, in test_incident_hot_spots_desktop
    self.assertEqual(featureCount, int(7302))
AssertionError: 7286 != 7302
```

Error in Pro:

```
test_incident_hot_spots_pro (patterns_tests.IncidentHotSpotsTestCase.IncidentHotSpotsTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentHotSpotsTestCase.py", line 75, in test_incident_hot_spots_pro
    self.assertEqual(featureCount, int(7302))
AssertionError: 7286 != 7302
```

## Steps to Reproduce (for bugs)
1. Open command prompt in solutions-geoprocessing-toolbox repo folder
2. cd .\utils\test
3. .\TestKickStart.bat

## Context
During 10.5 testing of tools with automated tests.

## Your Environment
* Version used: ArcMap 10.5 and ArcGIS Pro 1.4.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): Windows 10

**Comment by csmoore** [comment]
This fails for me also (in ArcMap 10.4.1) - but with different error:

```
test_incident_hot_spots_desktop (patterns_tests.IncidentHotSpotsTestCase.IncidentHotSpotsTestCase)Traceback (most recent call last):
  File "C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentHotSpotsTestCase.py", line 89, in test_incident_hot_spots_desktop
    self.fail('Exception in IncidentHotSpots_iaTools for Desktop toolbox \n' + msg)
AssertionError: Exception in IncidentHotSpots_iaTools for Desktop toolbox
Failed to execute. Parameters are not valid.
ERROR 000732: Input Incident Boundary Features: Dataset C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\data\scratch.gdb\outputHotSpots does not exist or is not supported
ERROR 000732: Bounding Polygons Defining Where Incidents Are Possible: Dataset C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\data\scratch.gdb\outputHotSpots does not exist or is not supported
Failed to execute (IncidentHotSpots).
```

**Comment by csmoore** [comment]
Verify with/after #563

**Comment by mfunk** [comment]
Verified running in test cases.
