### ISSUE TITLE
RefGrid.py script threw "TypeError: 'float object cannot be interpreted as an integer" error

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#615]
I ran the "Define Reference Grid from Area" gp tool from ArcGIS Pro 2.0 using the following parameters:
- Input Grid Area: using layer InputGRGArea (this feature class can be found Development\Commercial\GitHubIssueReplicationData\solutions-geoprocessing-toolbox\Issue_615\Issue_615.gdb)
- Reference Grid: MGRS
- Grid Square Size: 1000M_GRID
- Large Grid Handling: ALLOW_LARGE_GRIDS

Received the following error:

Traceback (most recent call last):
  File "C:\Backup\Projects\GriddedReferenceGraphic\solutions-geoprocessing-toolbox-mf-581-mgrs-in-grg (1)\solutions-geoprocessing-toolbox-mf-581-mgrs-in-grg\clearing_operations\scripts\GRGTools.py", line 514, in execute
    out_grid = RG.Build(parameters[3].value)
  File "C:\Backup\Projects\GriddedReferenceGraphic\solutions-geoprocessing-toolbox-mf-581-mgrs-in-grg (1)\solutions-geoprocessing-toolbox-mf-581-mgrs-in-grg\clearing_operations\scripts\RefGrid.py", line 162, in Build
    polys = polys + _handleGridSquares(sq[i], currentValue, AOIPoly)
  File "C:\Backup\Projects\GriddedReferenceGraphic\solutions-geoprocessing-toolbox-mf-581-mgrs-in-grg (1)\solutions-geoprocessing-toolbox-mf-581-mgrs-in-grg\clearing_operations\scripts\RefGrid.py", line 430, in _handleGridSquares
    for n in range(int(math.floor(minN / interval) * interval), int(maxN), interval):
TypeError: 'float' object cannot be interpreted as an integer
Failed to execute (DefineReferenceGridFromArea).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Dbarnes1** [comment]
I have also been able to replicate this issue this morning

**Comment by adgiles** [comment]
Fix in PR #623

**Comment by elinz** [comment]
Verified fix in dev branch. closing issue.
