### ISSUE TITLE
Clearing Ops units tests are failing on delete scratch GDB step at Pro 2.1

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#627]
Several Clearing Ops units tests are failing on the delete scratch GDB step at Pro 2.1

Error:

```
Exception ignored in: <bound method ReferenceGrid.__del__ of <scripts.RefGrid.ReferenceGrid object at 0x00000281C924E198>>
Traceback (most recent call last):
  File "C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\clearing_operations\scripts\RefGrid.py", line 43, in __del__
    arcpy.Delete_management(self.scratch_workspace)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4022, in Delete
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4019, in Delete
    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000601: Cannot delete C:\Users\----\AppData\Local\Temp\scratch\HXJOAH.gdb.  May be locked by another application.
Failed to execute (Delete).
```

## Steps to Reproduce (for bugs)

1. On **Pro 2.1**
2. Run Units Test Driver (TestKickstartPro.bat)
3. Note Clearing Ops error (above)

## Your Environment

* Versions used: 
Current Dev branch
Pro 2.1 Beta 1 (2.1.9865)
Windows 10

**Comment by csmoore** [comment]
Recommend closing this as a duplicate of #634 - combined/added the output above with the existing issue
